CREATE TABLE "HW12_container" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_container_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HW12_error" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_error_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"containerId" integer NOT NULL,
	"errorMessage" varchar(1024) NOT NULL,
	"explaination" varchar(2048) NOT NULL,
	"suggestedFix" varchar(2048) NOT NULL,
	"occurredAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "HW12_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "HW12_status" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "HW12_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"containerId" integer NOT NULL,
	"status" varchar(256) NOT NULL,
	"checkedInAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "HW12_error" ADD CONSTRAINT "HW12_error_containerId_HW12_container_id_fk" FOREIGN KEY ("containerId") REFERENCES "public"."HW12_container"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "HW12_status" ADD CONSTRAINT "HW12_status_containerId_HW12_container_id_fk" FOREIGN KEY ("containerId") REFERENCES "public"."HW12_container"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "HW12_post" USING btree ("name");